CHANGELOG.rst
playbooks/tools/dist-upgrade.yml

This playbook can be used to upgrade hosts from Debian Wheezy to Debian
Jessie (and similar).
Fixes #101

Add 'tools/dist-upgrade.yml' playbook

---

playbooks/bootstrap.yml

connecting as root -> $USER
connecting with other user -> that user's name
Now *this* solves the issue we discussed on IRC today.

Change which user name will be created.

---

docs/custom-features.rst
docs/guides/getting-started.rst
docs/guides/linux-containers.rst
docs/guides/local-apt-repository.rst
docs/introduction.rst
docs/playbook-layout.rst

You do use spell checking in your editor, do you :smile: ?

Fixed spelling and updated Debian jessie references (which is now stable).

---

CHANGELOG.rst
playbooks/bootstrap.yml

At first I only found the typo in `playbooks/bootstrap.yml` and hold the PR back because fixing one typo is lame … :smile:

Fixed spelling.

---

docs/copyright.rst

A small typo error, nothing much

Changed "his program" to "This Program"

---

CHANGELOG.rst

Automate all the things :wink:

Added sed script to rewrite hosts file. Related to #212.

---

README.rst

* Changed table format because this one is supported by
[Riv](https://github.com/Rykka/riv.vim).
https://github.com/ypid/debops-playbooks/tree/rework-role-overview

Added more roles to the README.

---

CHANGELOG.rst
playbooks/service/owncloud.yml

Related to https://github.com/debops/ansible-owncloud/pull/30

Moved roles dependencies from debops.owncloud to owncloud playbook.

---

playbooks/service/tinc.yml

Related to https://github.com/debops/ansible-tinc/pull/16

Moved roles dependencies from debops.tinc to tinc playbook.

---

playbooks/service/subnetwork.yml

https://github.com/debops/ansible-subnetwork/issues/13

Updated debops.subnetwork playbook.

---

playbooks/service/libvirtd.yml

Related to https://github.com/debops/ansible-libvirtd/pull/3.

Updated debops.libvirtd playbook.

---

CHANGELOG.rst
playbooks/service/preseed.yml

Related to https://github.com/debops/ansible-preseed/pull/12.

Updated playbooks/service/preseed.yml.

---

galaxy/requirements-manual.txt
galaxy/requirements-testing.txt
galaxy/requirements-testing.yml
scripts/get_all_referenced_roles

Following the suggestions by @drybjed
https://github.com/debops/debops-playbooks/pull/255#issuecomment-222913062

Made `galaxy/*` files reproducible again.

---

CHANGELOG.rst

https://github.com/debops/docs/issues/154#issuecomment-230577060

Refer to the latest stable version of Semantic Versioning e. g. v2.0.0.

---

.gitignore
CHANGELOG.rst
README.rst
docs/custom-environment.rst
docs/custom-features.rst
docs/guides/getting-started.rst
docs/guides/linux-containers.rst
docs/guides/local-apt-repository.rst
docs/guides/service-ports.rst
docs/includes/all.rst
docs/includes/all_from_subdir.rst
docs/playbook-layout.rst

Mainly an automated edit. Hope it does not break anything.
Depends on: https://github.com/debops/docs/pull/173

Use global.rst hyperlink definition.

---

playbooks/service/docker.yml

Depends on ansible-docker role.

Renamed Docker role docker_ variables to docker__.

---

.gitignore
CHANGELOG.rst
README.rst

Related to: https://github.com/debops/debops/issues/154

Add CII Best Practices badge to the repository README

---

playbooks/library/database/ldap/ldap_attr.py
playbooks/library/database/ldap/ldap_entry.py

This fixes [issue #30 in debops.slapd raised by @bhedana](https://github.com/debops/ansible-slapd/issues/30).

Added type info to argument_spec to ldap_*.py.

---

playbooks/service/samba.yml
playbooks/service/stunnel.yml

Updating Samba and stunnel playbooks per #192 .

Moved dependencies for Samba and stunnel services from roles to playbooks

---

CHANGES.rst
playbooks/service/dnsmasq.yml

Related to: https://github.com/debops/ansible-dnsmasq/pull/22

Update the debops.dnsmasq_ playbook to the new version

---

CHANGES.rst
playbooks/service/lxc.yml

Related to: https://github.com/debops/ansible-lxc/pull/29

Update the debops.lxc playbook to the new version

---

CHANGES.rst
playbooks/service/owncloud-apache.yml

Related to: https://github.com/debops/ansible-owncloud/pull/78

Update the debops.owncloud with Apache playbook to the new version

---

playbooks/service/apache.yml
playbooks/service/owncloud-apache.yml
playbooks/service/owncloud-nginx.yml

Related to: https://github.com/debops/ansible-owncloud/pull/79
Related to: https://github.com/debops/ansible-apache/pull/8

Update Ansible tags for ownCloud and Apache playbooks

---

playbooks/service/owncloud-apache.yml

Related to: https://github.com/debops/ansible-owncloud/pull/81

Update owncloud-apache.yml playbook

---

CHANGES.rst
galaxy/requirements-testing.txt
galaxy/requirements-testing.yml
galaxy/requirements.txt
galaxy/requirements.yml
playbooks/service/persistent_paths.yml
playbooks/sys/all.yml
playbooks/sys/persistent_paths.yml

Related to: https://github.com/debops/debops-playbooks/issues/333

Add `debops.persistent_paths` role and its corresponding playbook

---

CHANGES.rst
playbooks/common.yml

Inspired by: https://github.com/debops/ansible-php/pull/20#issuecomment-276629927
Related to: https://github.com/ansible/ansible/issues/18375
Ref: https://www.ansible.com/security
Ref: https://blog.fefe.de/?ts=a6895f34
Ref: https://www.computest.nl/advisories/CT-2017-0109_Ansible.txt

Terminate playbook execution if a vulnerable Ansible version is used

---

CHANGES.rst
playbooks/library/database/ldap/ldap_attr.py
playbooks/library/database/ldap/ldap_entry.py

Ref: https://github.com/ypid/ypid-ansible-common/blob/master/bin/debops-optimize

debops-optimize

---

CHANGES.rst
playbooks/net/dnsmasq-persistent_paths.yml
playbooks/net/dnsmasq-plain.yml
playbooks/service/dnsmasq-persistent_paths.yml
playbooks/service/dnsmasq-plain.yml
playbooks/service/dnsmasq.yml

Depends on: https://github.com/debops/ansible-dnsmasq/pull/24

Add debops.dnsmasq playbook for use with debops.persistent_paths

---

CHANGES.rst
templates/debops__tpl_macros.j2

Opened to keep track of PR which make use of this. I would propose to wait and merge all at once when this has been properly tested.

Add `flattened` Jinja filter to debops__tpl_macros.js

---

playbooks/service/nginx.yml

Depends on: https://github.com/debops/ansible-nginx/pull/156

Update debops.nginx playbook

---

templates/debops__tpl_macros.j2

These are some suggestions following #363. However, I'm struggling a bit.
* `get_realm_yaml_list`: I didn't try to figure out what's that for yet
* `get_XXXX_version`: No idea what they are for
* `indent`: Already nicely commented, congrats 👍  Would still help to have a short description of the arguments though
* `merge_dict`: This is a tough one. Couldn't follow all the code paths yet. What is the `dict_key` for? In which case is this `lookup("flattened")` used?

Add some comments describing the macros

---

CHANGES.rst
playbooks/service/owncloud-apache.yml
playbooks/service/owncloud-nginx.yml

Depends on: https://github.com/debops/ansible-owncloud/pull/83

Update debops.owncloud playbooks

---

CHANGES.rst
playbooks/net/tinc-persistent_paths.yml
playbooks/net/tinc-plain.yml
playbooks/service/tinc-persistent_paths.yml
playbooks/service/tinc-plain.yml
playbooks/service/tinc.yml

Depends on: https://github.com/debops/ansible-tinc/pull/38
Depends on: https://github.com/drybjed/ansible-tinc/pull/2

Add debops.tinc playbook for use together with debops.persistent_paths

---

docs/guides/getting-started.rst

Links to doc

---

docs/guides/getting-started.rst

Replaced links to github by links to doc.debops

---

playbooks/service/apt.yml
playbooks/service/gitlab.yml

Related to: debops/ansible-gitlab#98

Update gitlab playbook
