debops/debops-playbooks

playbooks/bootstrap.yml
If one does not have any user on the host, he connects
with root. Then the remote user is root, and ansible_ssh_user seems to
represent the remote user.
=> Do not use ansible_ssh_user as admin user

CHANGELOG.rst, playbooks/bootstrap.yml, playbooks/common.yml
These variables make more sense at the bootstrap stage instead of during
normal playbook runs.
=> Move hostname/domain vars to bootstrap.yml

CHANGELOG.rst, playbooks/root.yml, playbooks/templates/etc/ansible/facts.d/root.fact.j2
Changes in playbook or inventory that redefine 'root.yml' paths won't
affect existing installation anymore.
Default service home directory has been changed from '/var/lib' to
'/var/local' to avoid collisions with system packages in the future.
=> Add new root.yml paths and preserve defined

playbooks/bootstrap.yml
You should be able to correctly specify list of SSH keys for admin
account.
=> Fix bootstrap_admin_sshkeys variable

playbooks/bootstrap.yml
In a docker containers both setting the hostname and changing
/etc/hostname is prohibited.
=> Bootstrap: Do not set hostname in docker guest.

playbooks/lookup_plugins/file_src.py, playbooks/lookup_plugins/template_src.py
If a relative path in `template-paths` is specified, it will be treated as relative to the project root. This allows you to define in `.debops.cfg` ...
[paths]
template-paths: ansible/templates
... where you can store your project specific templates.
=> 'template-paths' accept relative paths to project root

CHANGELOG.rst, playbooks/bootstrap.yml
There are now more variables that define the administrator account,
admin account will be now a "system" account by default (UID < 1000).
Playbook checks if an account with a given name already exists and does
not change its parameters if it does. Admin account will be in more
groups by default ('admins' (passwordless sudo access), 'staff' and
'adm').
=> Changes to admin account created by bootstrap.yml

playbooks/bootstrap.yml
There is no `bootstrap_hostname` var
=> s/bootstrap_hostname/inventory_hostname in bootstrap.yml comments

playbooks/bootstrap.yml
Some vendors (at Ubuntu on DigitalOcean) don't have the package index files populated until apt-get update is first run.
And getting fresh packages on first install is good anyway.
=> Populate and update package index files before installing

CHANGELOG.rst
Fix the Link to point to CHANGES.rst inside the debobs script repo as CHANGELOG.md was converted
=> Followup to Convert Changelog to reStructuredText

galaxy/requirements-testing.yml, galaxy/requirements.yml
I am opening issue in debops to discuss this.  BBS with link.
=> Added requirements.yml files

docs/guides/getting-started.rst
Playing around with Sphinx and Pygments the problem was the "hostname"
line which might be uncommon/illegal in normal ini files.
Since Sphinx 1.3.5 this becomes a warning and in the DebOps projects,
warnings are handled as errors :)
https://github.com/sphinx-doc/sphinx/issues/1565
Disable ini highlighting for now.
=> The ini format used for hosts by Ansible might not be compatible for docs.

CHANGELOG.rst, playbooks/common.yml, playbooks/service/pki.yml
The new 'debops.pki' role has additional required roles that need to be
executed before it.
=> Update common and service/pki.yml playbooks

docs/credits.rst
Related to https://github.com/debops/debops/pull/146.
@drybjed Redundant with https://github.com/debops/debops/blob/master/docs/credits.rst? Maybe move to one project wide credits file or split it?
=> Added Robin Schneider as author.

CHANGELOG.rst, playbooks/service/subnetwork.yml
Related to https://github.com/debops/ansible-subnetwork/pull/10.
=> Moved roles dependencies from `debops.subnetwork` to subnetwork playbook.

playbooks/common.yml, playbooks/service/apt_cacher_ng.yml, playbooks/service/docker.yml, playbooks/service/mailman.yml, playbooks/service/nginx.yml, playbooks/service/ntp.yml, playbooks/service/owncloud.yml, playbooks/service/postfix.yml, playbooks/service/postgresql.yml, playbooks/service/postgresql_server.yml, playbooks/service/slapd.yml, playbooks/service/snmpd.yml, playbooks/service/sshd.yml, playbooks/service/subnetwork.yml, playbooks/service/tinc.yml
Related to https://github.com/debops/ansible-apt/pull/54.
=> Updated to reworked `debops.apt` role. Namespacing updates.

playbooks/service/apt_cacher_ng.yml
Related to https://github.com/debops/ansible-apt_cacher_ng/pull/4
=> Renamed `apt_cacher_ng__nginx_upstream` to `apt_cacher_ng__nginx__upsream`.

CHANGELOG.rst, playbooks/common.yml
=> Run `debops.apt` earlier in the `common.yml` playbook.

playbooks/bootstrap.yml, playbooks/library/database/ldap/ldap_attr.py, playbooks/library/database/ldap/ldap_entry.py
A cleanup to change "sudo" to "become" in comments and examples.
=> change 'sudo' to 'become' in comments and examples

README.rst
Instead of linking to the deprecated PHP playbook, go directly to the new one.
=> Link to new PHP playbook

playbooks/service/libvirtd.yml
libvirtd hosts need to forward packets, otherwise the hosted boxes
won't be able to speak with the outside world.
=> Fix ferm configuration for hosts using libvirtd.

playbooks/service/elasticsearch.yml
Role dependencies are not hard-coded anymore. See
debops/ansible-elasticsearch#12
=> Adjust elasticsearch playbook to recent role updates

playbooks/app/owncloud-apache.yml, playbooks/app/owncloud-nginx.yml, playbooks/service/owncloud-nginx.yml, playbooks/service/owncloud.yml
Prior, the Apache playbook was not run when calling `debops service/owncloud` or `debops app/owncloud`.
Nginx is still the default.
=> Fix ownCloud Apache playbook

docs/guides/getting-started.rst
Ansible 2.0 and higher where `ansible_ssh_user` is deprecated and replaced by `ansible_user`. [tallandtree_] - See as well: https://github.com/debops/ansible-bootstrap/compare/3a369b104713...7059627d457a
=> ansible_ssh_user -> ansible_user

CHANGES.rst, playbooks/service/cryptsetup-persistent_paths.yml, playbooks/service/cryptsetup-plain.yml, playbooks/service/cryptsetup.yml, playbooks/sys/cryptsetup-persistent_paths.yml, playbooks/sys/cryptsetup-plain.yml
Related to: https://github.com/debops/ansible-cryptsetup/pull/23
I would propose that once a role has gotten more then one playbook, the plain/stripped down playbook gets renamed to `cryptsetup-plain.yml` (or a more precise name if there is one, see below) and a new `cryptsetup.yml` playbook gets created which includes all the role playbooks. This way, the user can still call the main/meta playbook and does not know which particular variant of the playbook is used for a particular host.
@drybjed Do you agree with this proposal?
Other examples: https://github.com/debops/ansible-owncloud/tree/master/docs/playbooks
=> Update the debops.cryptsetup_ playbook to the new version

CHANGES.rst, COPYRIGHT, README.rst, templates/debops__tpl_macros.j2
Reason: Needed because there are a few macros which currently get inlined/duplicated into the different role’s templates which is not really maintenance friendly. As you can see this as the versions of the `merge_dict` macro already differs slightly in [debops.ifupdown](https://github.com/debops/ansible-ifupdown/blob/master/templates/lookup/ifupdown__combined_interfaces.j2) and [debops.cron](https://github.com/debops/ansible-cron/blob/master/templates/lookup/cron__combined_jobs.j2). Such deviations can automatically be resolved by debops-optimize when there are common files which can be identified by filename and updated.
=> Add commonly used set of Jinja2 macros to the repository

CHANGES.rst, playbooks/common.yml
The releases v2.1.4 and v2.2.1 did not fully support all DebOps roles which is why `s/stable-2\.[12]/` branches where required for the time being. Now that the latest versions of those branches have been released we can properly check for them.
=> Require v2.1.5 or v2.2.2 instead of unreleased Ansible releases

playbooks/service/gitlab.yml, playbooks/service/owncloud-apache.yml, playbooks/service/owncloud-nginx.yml
Related to: https://github.com/debops/ansible-owncloud/pull/82
This prepares for the drop of legacy variables.
=> Update debops.owncloud playbooks

playbooks/common.yml
The "resources" role should come before the role "ferm" so that it is possible to use in the rules the files that are written by the role "resources"
=> Resources before Ferm

CHANGES.rst
The assertion output already contains a hint that the user should check the changelog for more details. Therefore I clarified in the changelog why those minimal versions are enforced instead of adding it as a comment in the code as suggested in https://github.com/debops/debops-playbooks/issues/375#issuecomment-316607127.
=> Clarify enforced minimal Ansible version

playbooks/sys/all.yml
By performing LVM setup before nfs_server task,
user can share directory under LVM partition at once.
Signed-off-by: tharada <harada.tomoyuki03@gmail.com>
=> perform lvm task before nfs_server

playbooks/service/librenms.yml
Signed-off-by: tharada <harada.tomoyuki03@gmail.com>
Brace-mismatch found in `playbooks/service/librenms.yml`, and this causes failure when configuring librenms service like below.
```
TASK [debops.logrotate : Divert the custom log rotation config] **********************************************************************************************
fatal: [nms.example.com]: FAILED! => {"failed": true, "msg": "[u'{{ php__logrotate__dependent_config }}', u'{{ librenms__logrotate__dependent_config }]']: template error while templating string: unexpected '}'. String: {{ librenms__logrotate__dependent_config }]"}
```
This commit just fixes the mismatch.
=> fix brace-mismatch in playbook
